local _, UHUI = ...

BINDING_HEADER_UHUI = "|cFF8080FFUnhaltedUI|r"
BINDING_NAME_UHUIHIDEBARS = "Hide ActionBars OOC"
BINDING_NAME_UHUILEAVEPARTY = "Leave Party"
BINDING_NAME_UHUIOPENVAULT = "Open Great Vault"